services:
  postgresql:
    image: postgres:latest
    networks:
      - db
      - web
    volumes:
      - ./db/init/create-table.sql:/docker-entrypoint-initdb.d/create_tables.sql
      - ./db/data:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_USER: pgsql
      POSTGRES_PASSWORD: pgsql
      POSTGRES_DB: measurements
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d measurements -U pgsql"]
      interval: 10s
      timeout: 10s
      retries: 20
      start_period: 10s
  pgadmin:
    depends_on:
      postgresql:
        condition: service_healthy
    image: dpage/pgadmin4:latest
    networks:
      - db
    ports:
      - 80:80
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: petru.rotaru@stud.acs.upb.ro
      PGADMIN_DEFAULT_PASSWORD: pgadmin
      PGADMIN_CONFIG_CONSOLE_LOG_LEVEL: 50
  api:
    depends_on:
      postgresql:
        condition: service_healthy
    build:
      .
    networks:
      - web
    ports:
      - 5000:5000

networks:
  db:
  web:
